project:
  type: website
  output-dir: docs

website:
  title: "TLM_PROJECT"
  favicon: images/clipboard-3772666577.png
  sidebar:
    logo: images/clipboard-3772666577.png
    style: "docked"
    search: true            # Añade un buscador automático
    contents:
      - href: index.qmd    # <--- Este será el enlace de inicio
        text: "Introducción"
      - section: "Descripción general"
        contents:
          - overview.qmd
      - section: "Objetivos"
        contents:
          - so1.qmd
          - so2.qmd
          - so3.qmd
          - so4.qmd
          - so5.qmd
          - so6.qmd
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Contexto"
        href: overview.qmd
    right:
      - icon: github
        href: https://github.com/TLM-PROJECT/TLM-PROJECT.github.io.git
        aria-label: GitHub
        target: _blank
format:
  html:
    theme: 
      - flatly
      - custom.scss
    toc: true
    toc-title: "En esta sección:" 
    toc-location: right      # El TOC de la página va a la derecha
    toc-depth: 6
    #number-sections: true
