project:
  type: website
  output-dir: docs
  title: "CMS Phase 3: Seeing the forest for the trees"

website:
  bread-crumbs: false
  page-footer: 
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/), with theme from [vetiver] (https://github.com/rstudio/vetiver.rstudio.com) and adapted from https://nasa-openscapes.github.io "
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Project overview"
        contents:
          - href: index.qmd
      - section: "Geospatial products"
        contents:
          - href: BiasCorrected.qmd
      - section: "User preferences for the generation of tree lists"
        contents:
          - href: SurveyTL.qmd
      - section: "Demos"
        contents:
          - href: Demo1.qmd
          
format:
  html:
    theme:
      - sandstone
      - cosmo
    code-link: true
    callout-appearance: simple
    toc: true
    toc-title: Contents
    toc-location: right

editor: visual