---
title: "TLM-PROJECT"
---

## Project overview

## Geospatial products:

We produced various geospatial datasets for managing western US forests. Our methodology 

## Data use for natural resource managers:

This data is valuable for quantifying/baselining/monitoring forest carbon stocks, assessing spatial distribution of fuels, quantifying timber volume across large areas, assessing wildfire risk, investigating wildlife distributions, and other natural resource management applications.

## Data summary:

-   Timber attributes: basal area, trees per hectare, stand density index, quadratric mean diameter, volume, above ground biomass, etc.

-   Fuel attributes: canopy base height, canopy bulk density, canopy fuel load, etc.

-   Wildlife attributes: snag density, crown competition factor

-   Spatial resolution & extent: 30-m, western USA

-   Temporal resolution & extent: Annual, 1985-2020 (update to present in progress)

-   Precision: R^2^: 0.81, RMSE: 47.3 Mg/ha (e.g., for 2020 ABG; available for other attributes)

## Data availability:

Data are currently available by individual request but will be made permanently available through the ORNL-DAAC and other public data repositories.

## Help us improve our prdducts

We are conducting a survey to improve our products for a third phase of our project. If you use or produce geospatial data for natural resource management, please take our survey. You can scan the following QR code or directly use this [Link](https://forms.office.com/r/TSx9CYnGnw). Thank you very much for your valuable input.

