---
title: "2. Usuarios finales"
format: html
editor: visual
---

# Preferencias de los usuarios finales (Preferences from end users)

El paquete de trabajo para este objetivo se ha organizado en dos tareas. La primera se ha centrado en contactar con grupos de usuarios finales potenciales y diseñar y entregar un cuestionario para identificar las respuestas más importantes para las aplicaciones de gestión. En la segunda tarea, se han implementado sesiones interactivas para recopilar respuestas a los cuestionarios de AHP y obtener ponderaciones preferenciales para las variables identificadas en la tarea anterior. Estas ponderaciones se han utilizado para crear una métrica de error para las etapas posteriores del proyecto.

## Tarea 2.1. Contacto inicial e identificación de variables y necesidades clave

Se ha contactado con un total de – usuarios potenciales provenientes de cinco grupos diferentes:

1.  Gestores forestales de la administración pública

2.  Propietarios privados de terrenos forestales

3.  Personal de extinción de incendios

4.  Científicos de diversas universidades y centros de investigación

5.  Profesionales de empresas privadas del sector.

Se ha trabajado con ellos en dos sesiones interactivas. En la primera sesión se han obtenido de los usuarios las variables que facilitarían su trabajo,  verificando que: 1) se pueden calcular utilizando datos de los gráficos SNFI y 2) si están disponibles en formato de mapa.  



```{mermaid}

---
config:
  theme: forest
  look: handDrawn 
  themeVariables:
    font-size: 10px 
    lineColor: '#F8B229'
    secondaryColor: '#006100'
    tertiaryColor: '#fff'
---
graph TD
  B[Campos de aplicación]
  
  B --> C[**Selvicultura**] 
  B --> D[**Incendios**]
  B --> E[**Biodiversidad**]
  
  C --> C1[Área Basimétrica 
  Altura dominante 
  Volumen 
  Densidad 
  ]
  D --> D1[Modelo de Combustible de Superficie 
  Altura de la Base del Estrato de Copas 
  Altura del Estrato de Copas 
  Densidad de combustible 
  Carga de combustible de copas 
  Cantidad de horjarasca en suelo 
  ]
  style D1 font-size: 11px
  E --> E1[Diversidad estructural
  Diversidad taxonómica
  Diversidad funcional 
  ]
```

En la segunda sesión,se han utilizado estas variables para realizar encuestas AHP, con el fin de obtener información sobre las necesidades y cuantificar las preferencias de los gestores forestales y otros usuarios finales.

## Tarea 2.2. Caracterización de las preferencias de los usuarios finales

### Identificación de necesidades a partir de las primeras sesiones interactivas y diseño de cuestionarios AHP



"Los microdatos de estas encuestas se depositarán en la base de datos ARCES del Centro de Investigaciones Sociológicas (CIS), como máximo, 12 meses después de la finalización del proyecto."


### Segunda sesión interactiva para cuestionarios AHP



### Obtención de la función de pérdida para las etapas de ajuste del modelo a partir de los resultados de la encuesta AHP.
Las respuestas al AHP se han utilizado para derivar ponderaciones de preferencia para las variables de cada usuario. Las ponderaciones de preferencia se promedian dentro de los grupos y tanto las preferencias individuales de los usuarios como las grupales se analizan mediante técnicas de agrupamiento. 
