---
title: "6. Comunicación"
format: html
editor: visual
---

# Comunicación y divulgación para maximizar el uso de los resultados de nuestra investigación.

Este paquete de trabajo incluye una única tarea cuyo objetivo es maximizar la transferencia de conocimiento a los gestores y profesionales forestales, la comunidad científica y la sociedad. La interacción con los usuarios potenciales es uno de los componentes clave de la investigación propuesta y este paquete de trabajo incluye acciones específicas para garantizar que la comunicación sea bidireccional y que los usuarios finales reciban la información necesaria para comprender cómo desarrollamos este proyecto y cómo pueden beneficiarse de sus resultados. En esta sección, explicamos en detalle la tarea clave que desarrollaremos para lograr este objetivo. En las secciones 4.3 a 4.5 se presenta una visión general de nuestra estrategia de comunicación, que describe cómo difundiremos nuestros resultados a la comunidad científica, los gestores y profesionales forestales y la sociedad.

A continuación se detalla el listado de artículos publicados

## Tarea 6.1 Seminarios y tutoriales sobre el uso de mapas de listas de árboles

### Seminarios

### Materiales online
